name: databricks_scripts_ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18


      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Hello world action
        env:
          DB_TOKEN: ${{ secrets.DB_NONPROD_TOKEN }}
        run: echo ${{secrets.DB_NONPROD_TOKEN}}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
            envkey_DEBUG: false
            envkey_SOME_API_KEY: "123456abcdef"
            envkey_SECRET_KEY: ${{ secrets.DB_NONPROD_TOKEN }}
            file_name: .env
      - name: Hello world action
        run: cat .env
