name: Airflow Lint DAGs

on:
  push:
    branches:
      - master
  build:
    runs-on: ubuntu-latest
#    container:
#      image: apache/airflow:2.1.0
    steps:
      - name: Install airflow and run pylint
        run: |
          pip install apache-airflow==2.1.0
          pip install pylint pylint-airflow
          pylint --load-plugins=pylint_airflow --disable=missing-docstring dags