name: Airflow Lint DAGs

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: apache/airflow:2.1.0
    steps:
      - run: ls -l
      - uses: actions/checkout@v2
      - name: Install airflow and run pylint
        run: |
          pip install pylint pylint-airflow
          pylint --load-plugins=pylint_airflow --disable=missing-docstring dags