name: Airflow Lint DAGs

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    name: Airflow ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install airflow and run pylint
        run: |
          pip install apache-airflow==2.1.0
          pip install pylint pylint-airflow
          pylint --load-plugins=pylint_airflow  dags